# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /feedstock/recipe, last modified Sat Feb 10 00:08:15 2024
# ------------------------------------------------

package:
  name: cryptography
  version: 42.0.2
source:
  sha256: e0ec52ba3c7f1b7d813cd52649a5b3ef1fc0d433219dc8c93827c57eab6cf888
  url: https://pypi.io/packages/source/c/cryptography/cryptography-42.0.2.tar.gz
build:
  number: '0'
  script:
    - export OPENSSL_DIR=$PREFIX
    - /croot/cryptography_1707523700518/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
      -m pip install . -vv --no-deps --no-build-isolation
  string: py39hdda0065_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.38 h2a08ee3_1
    - binutils_linux-64 2.38.0 hc2dff05_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_0
    - gxx_impl_linux-64 11.2.0 h1234567_1
    - gxx_linux-64 11.2.0 hc2dff05_0
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.38 h1181459_1
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-devel_linux-64 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - rust 1.71.1 h06a4308_0
    - rust_linux-64 1.71.1 h6a678d5_0
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - ca-certificates 2023.12.12 h06a4308_0
    - cffi 1.15.1 py39h5eee18b_3
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.4 h6a678d5_0
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.13 h7f8727e_0
    - pip 23.3.1 py39h06a4308_0
    - pycparser 2.21 pyhd3eb1b0_0
    - python 3.9.18 h955ad1f_0
    - readline 8.2 h5eee18b_0
    - semantic_version 2.8.5 pyhd3eb1b0_0
    - setuptools 68.2.2 py39h06a4308_0
    - setuptools-rust 1.8.1 py39h06a4308_0
    - sqlite 3.41.2 h5eee18b_0
    - tk 8.6.12 h1ccaba5_0
    - tomli 2.0.1 py39h06a4308_0
    - tzdata 2023d h04d1e81_0
    - wheel 0.41.2 py39h06a4308_0
    - xz 5.4.5 h5eee18b_0
    - zlib 1.2.13 h5eee18b_0
  run:
    - cffi >=1.12
    - libgcc-ng
    - openssl >=3.0.13,<4.0a0
    - python >=3.9,<3.10.0a0
test:
  commands:
    - pip check
    - pytest -n auto
  requires:
    - certifi
    - cryptography-vectors 42.0.2.*
    - pip
    - pretend
    - pytest >=6.2.0
    - pytest-benchmark
    - pytest-cov
    - pytest-xdist
  source_files:
    - pyproject.toml
    - tests
about:
  description: 'Cryptography is a package which provides cryptographic recipes and

    primitives to Python developers. Our goal is for it to be your

    "cryptographic standard library". It supports Python 3.6+ and PyPy3 7.2+.

    cryptography includes both high level recipes and low level interfaces to

    common cryptographic algorithms such as symmetric ciphers, message digests,

    and key derivation functions.

    '
  dev_url: https://github.com/pyca/cryptography
  doc_url: https://cryptography.io/
  home: https://github.com/pyca/cryptography
  license: Apache-2.0 OR BSD-3-Clause
  license_family: OTHER
  license_file:
    - LICENSE
    - LICENSE.APACHE
    - LICENSE.BSD
  summary: Provides cryptographic recipes and primitives to Python developers
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: ad19032b-c153-4098-a39d-8d21b6294704
  recipe-maintainers:
    - chenghlee
    - jakirkham
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/cryptography-feedstock.git
  sha: 74de5260074507746ef1572c74750a2c5af33a0e
