# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /feedstock/recipe, last modified Wed Aug 16 17:03:45 2023
# ------------------------------------------------

package:
  name: platformdirs
  version: 3.10.0
source:
  sha256: b45696dab2d7cc691a3226759c0d3b00c47c8b6e293d96f6436f733303f77f6d
  url: https://pypi.io/packages/source/p/platformdirs/platformdirs-3.10.0.tar.gz
build:
  number: '0'
  script: /croot/platformdirs_1692205439124/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py39h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - ca-certificates 2023.05.30 h06a4308_0
    - editables 0.3 py39h06a4308_0
    - hatch-vcs 0.3.0 py39h06a4308_0
    - hatchling 1.18.0 py39h06a4308_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.4 h6a678d5_0
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.10 h7f8727e_0
    - packaging 23.0 py39h06a4308_0
    - pathspec 0.10.3 py39h06a4308_0
    - pip 23.2.1 py39h06a4308_0
    - pluggy 1.0.0 py39h06a4308_1
    - python 3.9.17 h955ad1f_0
    - readline 8.2 h5eee18b_0
    - setuptools 68.0.0 py39h06a4308_0
    - setuptools-scm 7.1.0 py39h06a4308_0
    - sqlite 3.41.2 h5eee18b_0
    - tk 8.6.12 h1ccaba5_0
    - tomli 2.0.1 py39h06a4308_0
    - trove-classifiers 2023.3.9 py39h06a4308_0
    - typing-extensions 4.7.1 py39h06a4308_0
    - typing_extensions 4.7.1 py39h06a4308_0
    - tzdata 2023c h04d1e81_0
    - wheel 0.38.4 py39h06a4308_0
    - xz 5.4.2 h5eee18b_0
    - zlib 1.2.13 h5eee18b_0
  run:
    - python >=3.9,<3.10.0a0
test:
  commands:
    - pip check
    - pytest tests -vv
  imports:
    - platformdirs
  requires:
    - appdirs
    - pip
    - pytest
    - pytest-mock
  source_files:
    - tests
about:
  description: 'About A small Python module for determining appropriate

    platform-specific dirs, e.g. a "user data dir".

    '
  dev_url: https://github.com/platformdirs/platformdirs
  doc_url: https://platformdirs.readthedocs.io/
  home: https://github.com/platformdirs/platformdirs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A small Python module for determining appropriate platform-specific dirs,
    e.g. a "user data dir".
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 00649cbe-c25f-403e-a7ae-241b83f776b1
  recipe-maintainers:
    - adament
    - gaborbernat
  remote_url: git@github.com:AnacondaRecipes/platformdirs-feedstock.git
  sha: 523c5fef6185e3a10e97e3dc20a33e58b92fd824
