# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /feedstock/recipe, last modified Fri Dec  1 18:23:19 2023
# ------------------------------------------------

package:
  name: distro
  version: 1.8.0
source:
  fn: distro-1.8.0.tar.gz
  sha256: 02e111d1dc6a50abb8eed6bf31c3e48ed8b0830d1ea2a1b78c61765c2513fdd8
  url: https://pypi.io/packages/source/d/distro/distro-1.8.0.tar.gz
build:
  entry_points:
    - distro = distro.distro:main
  number: '0'
  script: /croot/distro_1701455004953/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
    -m pip install . --no-deps --ignore-installed --no-cache-dir -v --no-build-isolation
  string: py39h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - ca-certificates 2023.08.22 h06a4308_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.4 h6a678d5_0
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.12 h7f8727e_0
    - pip 23.3.1 py39h06a4308_0
    - python 3.9.18 h955ad1f_0
    - readline 8.2 h5eee18b_0
    - setuptools 68.0.0 py39h06a4308_0
    - sqlite 3.41.2 h5eee18b_0
    - tk 8.6.12 h1ccaba5_0
    - tzdata 2023c h04d1e81_0
    - wheel 0.41.2 py39h06a4308_0
    - xz 5.4.2 h5eee18b_0
    - zlib 1.2.13 h5eee18b_0
  run:
    - python >=3.9,<3.10.0a0
test:
  commands:
    - pip check
    - distro --help
  imports:
    - distro
  requires:
    - pip
about:
  description: distro provides information about the OS distribution it runs on, such
    as a reliable machine-readable ID, or version information.
  dev_url: https://github.com/python-distro/distro
  doc_url: https://distro.readthedocs.io
  home: https://github.com/python-distro/distro
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A much more elaborate replacement for removed Python's 'platform.linux_distribution()'
    method
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: b827af54-a8be-41a9-b69d-9e137cfaadac
  recipe-maintainers:
    - abloemert
    - windelbouwman
  remote_url: git@github.com:AnacondaRecipes/distro-feedstock.git
  sha: 9f1209c474dbe2fc66978b39180ab37a0ac05d64
